- job:
    name: oslo.messaging-tox-py27-func-amqp1
    parent: openstack-tox-py27
    vars:
      tox_envlist: py27-func-amqp1

- job:
    name: oslo.messaging-tox-py27-func-rabbit
    parent: openstack-tox-py27
    vars:
      tox_envlist: py27-func-rabbit
      bindep_profile: rabbit

- job:
    name: oslo.messaging-telemetry-dsvm-integration-amqp1
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-telemetry-dsvm-integration-amqp1/run.yaml
    post-run: playbooks/oslo.messaging-telemetry-dsvm-integration-amqp1/post.yaml
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/devstack-plugin-amqp1
      - openstack/oslo.messaging
      - openstack/panko
      - openstack/telemetry-tempest-plugin
      - openstack/heat-tempest-plugin
      - openstack/heat
      # following are required when DEVSTACK_GATE_HEAT, which this
      # job turns on
      - openstack/dib-utils
      - openstack/diskimage-builder


- job:
    name: oslo.messaging-telemetry-dsvm-integration-rabbit
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-telemetry-dsvm-integration-rabbit/run.yaml
    post-run: playbooks/oslo.messaging-telemetry-dsvm-integration-rabbit/post.yaml
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/oslo.messaging
      - openstack/panko
      - openstack/telemetry-tempest-plugin
      - openstack/heat-tempest-plugin
      - openstack/heat
      # following are required when DEVSTACK_GATE_HEAT, which this
      # job turns on
      - openstack/dib-utils
      - openstack/diskimage-builder



- project:
    check:
      jobs:
        - oslo.messaging-tox-py27-func-amqp1:
            voting: false
        - oslo.messaging-tox-py27-func-rabbit

        - oslo.messaging-telemetry-dsvm-integration-rabbit
        - oslo.messaging-telemetry-dsvm-integration-amqp1:
            voting: false
    gate:
      jobs:
        - oslo.messaging-telemetry-dsvm-integration-rabbit
        - oslo.messaging-telemetry-dsvm-integration-amqp1:

